---
title: "Autores"
description: |
  O blog será mantido por Saulo Guerra, Paulo Felipe, Miguel Cleaver e Diego Castro. A nossa ideia é que mais pessoas possam colaborar no futuro para que o blog fique bastante rico e diversificado em informações.
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(fontawesome)
```

## Saulo Guerra [`r fa(name = "twitter", fill = "steelblue")`](https://twitter.com/sauloguerra)
Sou Formado em Ciência da Computação pela Universidade de Brasília (UnB). Trabalho no Ministério da Economia (ME) como Analista de Comércio Exterior. Possuo boa experiência com bancos de dados, SQL, programação mobile e programação web, principalmente web scraping. Adotei o R como principal linguagem de programação e venho aprofundando cada vez mais estudos e práticas na área de ciência de dados.

## Paulo Felipe [`r fa(name = "twitter", fill = "steelblue")`](https://twitter.com/paulofelipeao)
Sou economista com graduação e mestrado na Universidade Federal do Ceará - UFC. Atualmente, trabalho no Ministério da Economia - ME como Analista de Comércio Exterior. Tenho experiência com modelos microeconométricos e séries temporais. Além disso, venho estudando outras abordagens de análise de dados, como aprendizado de máquina e visualizações. Apesar de ter trabalhado com outros softwares estatísticos, o R tornou-se meu principal foco em relação a software/linguagem.

## Miguel Cleaver [`r fa(name = "twitter", fill = "steelblue")`](https://twitter.com/miguelcleaver)
Tenho graduação e mestrado em economia pela Universidade de Brasília (UnB). Trabalho no Ministério da Economia como Analista de Comércio Exterior. A maior parte do meu trabalho como Analista tem sido na área de limpeza, estruturação, análise e visualização de dados. Recentemente, tenho buscado me especializar em algoritmos preditivos supervisionados e não supervisionados. O R é minha principal linguagem de programação.

## Diego Castro [`r fa(name = "twitter", fill = "steelblue")`](https://twitter.com/DiegoAfonsodeC1)
Tenho graduação e mestrado em economia pela Universidade de Brasília (UnB) e mestrado em Análise de Dados pela Universidade de Sheffield (Reino Unido). Trabalho no Ministério da Economia como Analista de Comércio Exterior. Minha principal linguagem de programação é o R, mas também possuo experiência em Python. Me dediquei recentemente a estudar a utilização de imagens de satélite para previsão de renda em cidades brasileiras usando, para tanto, redes neurais convolucionais e modelos de regressão e classificação. 
