---
output:
  distill::distill_article:
    self_contained: false
description: |
  No dia 28/07/2016 a Secretaria de Comércio Exterior lançou o [Comex Vis](http://www.mdic.gov.br/comercio-exterior/estatisticas-de-comercio-exterior/comex-vis), uma ferramenta de visualização interativa de dados do comércio exterior brasileiro. Nesse post faremos alguns comentários sobre o Comex Vis e sobre a visualização de dados em geral.
# layout: post
title: "Comex Vis e a visualização de dados no Brasil"
date: 2016-07-30
# comments: true
# categories: [geral]
# published: true
preview: ../../images/comexvis.png
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
<!-- More -->

## O que é visualização de dados?

Nada mais é do que representar graficamente uma informação. Em outras palavras, é pegar uma informação abstrata, seja numérica ou textual, e representá-la com padrões visuais e formas geométricas.

Não se trata de uma novidade. Na verdade, isso é algo bem antigo, desde os primórdios da matemática já desenhavam gráficos e formas para representar dados. Porém, com os avanços tecnológicos e aprimoramentos no web design, as visualizações de dados estão alcançando outro patamar: deixando de ser apenas estáticas e passando a ser interativas.

## Por que isso é importante?

De alguma forma o cérebro humano compreende melhor padrões visuais geométricos do que planilhas com diversas linhas de números ou textos. Ou seja, ao olhar um gráfico, é muito mais provável que você compreenda aspectos dos dados representados mais rapidamente do que olhando uma tabela com os mesmos dados desse gráfico.

Portanto, a visualização de dados é um jeito mais simples e rápido de transmitir uma informação baseada em dados. Isso torna a visualização um artifício bastante poderoso para exploração, análise, insights e comunicação de dados, tornando os principais aspectos de um conjunto de dados algo mais rapidamente compreensivo e intuitivo.

## Visualizações interativas

O que temos notado é que as instituições mundo a fora que trabalham com divulgação de dados estão extrapolando as visualizações estáticas e aderindo a uma nova tendência de visualização interativas de dados. 

### E como anda esse tema no governo brasileiro? 

Felizmente parece estar indo bem! A seguir comentaremos sobre algumas iniciativas que mostram que o tema está evoluindo e cada vez mais presente na administração pública. De certa forma, isso é um avanço na transparência e na disseminação de dados públicos.

### Comex Vis

A SECEX (Secretaria de Comércio Exterior) lançou o [Comex Vis](http://www.mdic.gov.br/comercio-exterior/estatisticas-de-comercio-exterior/comex-vis): uma ferramenta de visualização interativa de dados do comércio exterior brasileiro. 

O objetivo do projeto é disponibilizar visualizações interativas dos dados de importação e exportação brasileira, cobrindo diversos aspectos e variáveis: parceiros comerciais, continentes, blocos, produtos e classificações, unidade da federação, etc.

Dessa forma, os consumidores dos dados de comércio exterior brasileiro terão uma alternativa para explorar e navegar nos dados de maneira fácil, sem precisar instalar ou conhecer nenhum outro tipo de ferramenta, bastando apenas internet e um navegador web.

O projeto foi completamente desenvolvido com plataformas livres e gratuitas, como o R e o [D3Plus](http://d3plus.org/), que é um pacote em javscript (baseado em [D3](https://d3js.org/)) capaz de criar visualizações interativas concisas, simples e bonitas. O D3Plus é responsivo, ou seja, se adapta e funciona bem em qualquer resolução de tela. Isso torna o Comex Vis funcional no computador, tablets e celulares.

Para integrar o R com o D3Plus, foi utilizado o pacote [HTMLWidgets](http://www.htmlwidgets.org/) que é capaz de utilizar pacotes em javascript para plotar visualizações com dados processados em R.

O Comex Vis foi inspirando em outros portais que também utilizam o D3Plus, como por exemplo o [The Observatory of Economic Complexity](http://atlas.media.mit.edu/en/), o [Data USA](http://datausa.io/) e o excelente [Data VIVA](http://www.dataviva.info/pt/), desenvolvido inicialmente com o apoio do governo de minas gerais. Vale muito a pena conhecer todos eles.

Ainda sobre visualização de dados de comércio exterior, o Comtrade, da ONU, tem um portal com diversas divulgações interativas: o [Comtrade Labs](http://comtrade.un.org/labs/)

### Outras iniciativas

Falando sobre divulgação de visualizações interativas no governo, o BNDES também tem uma página com diversos gráficos: o [BNDES Transparente](http://www.bndes.gov.br/SiteBNDES/bndes/bndes_pt/Institucional/BNDES_Transparente/). Lá é possível navegar e explorar dados sobre financiamentos do BNDES, taxas, prazos e desembolsos. Os gráficos foram construídos em [Tableau](http://www.tableau.com/pt-br), uma poderosa ferramenta de BI, porém, não é gratuito.

Existe também uma boa iniciativa do governo federal para criar uma plataforma com diversos tipos de visualizações sobre uma grande variedade de dados, o [VisPublica](http://vispublica.gov.br/vispublica/publico/catalogo.jsp). 

Já a FGV, utilizando dados públicos, criou uma ferramenta de visualização interativa de dados voltada para exploração dos desembolsos públicos, chamada [Transparência Orçamentária](http://dapp.fgv.br/transparencia-orcamentaria/).

O Banco Central também elaborou algumas visualizações para visualizar os dados do [Censo de Capitais Estrangeiros no Brasil](http://www.bcb.gov.br/Rex/CensoCE/port/resultados_censos.asp?idpai=CAMBIO). As visualizações foram geradas utilizando D3 e d3plus.

E você, conhece mais alguma iniciativa do setor público que utiliza visualização interativa de dados? Conte-nos nos comentários!

## Mais sobre visualização de dados

Se você está interessado em aprender mais sobre visualizações, assim como nós, recomendamos alguns sites que podem ajudar nessa jornada:

[DataViz Catalogue](http://www.datavizcatalogue.com/) - Um excelente catálogo explicativo sobre diversos tipos de visualizações, incluindo como e quando usá-las, seus pontos fortes e pontos fracos.

[O`Reilly - Effective Data Visualization](https://player.oreilly.com/videos/9781491917015) - Uma sequência de videos explorando diversos aspectos sobre visualização de dados. Infelizmente nem todos os videos são gratuitos, mas os gratuitos já são excelentes.
